#ifndef __FDOTOOL_SETTINGS_DEFAULTS_H
#define __FDOTOOL_SETTINGS_DEFAULTS_H

#define SETTINGS_PKCSTOOL_BIN_DEFAULT ""
#define SETTINGS_PKCSENGINE_LIB_DEFAULT ""
#define SETTINGS_OPENSSL_BIN_DEFAULT ""
#define SETTINGS_SMARTCARD_LIB_DEFAULT ""

#endif
