if (UNIX AND NOT APPLE)
    set(TOOLS_INSTALL_DIR ${CMAKE_INSTALL_LIBDIR}/fdotool)

    set(FDOTOOL_PKCS11_TOOL_BINARY pkcs11-tool)
    set(FDOTOOL_OPENSSL_BINARY ${TOOLS_INSTALL_DIR}/openssl)
    set(FDOTOOL_BIT4X_PKI_LIBRARY ${TOOLS_INSTALL_DIR}/libbit4xpki.so)
elseif (WIN32)
    set(TOOLS_INSTALL_DIR ${CMAKE_INSTALL_PREFIX}/fdotool)

    set(FDOTOOL_PKCS11_TOOL_BINARY pkcs11-tool)
    set(FDOTOOL_OPENSSL_BINARY ${TOOLS_INSTALL_DIR}/openssl)
    set(FDOTOOL_BIT4X_PKI_LIBRARY ${TOOLS_INSTALL_DIR}/libbit4xpki.so)
elseif (APPLE)
    set(TOOLS_INSTALL_DIR ${CMAKE_INSTALL_PREFIX}/fdotool)

    set(FDOTOOL_PKCS11_TOOL_BINARY pkcs11-tool)
    set(FDOTOOL_OPENSSL_BINARY ${TOOLS_INSTALL_DIR}/openssl)
    set(FDOTOOL_BIT4X_PKI_LIBRARY ${TOOLS_INSTALL_DIR}/libbit4xpki.so)
else ()
    set(TOOLS_INSTALL_DIR ${CMAKE_INSTALL_PREFIX}/fdotool)

    set(FDOTOOL_PKCS11_TOOL_BINARY pkcs11-tool)
    set(FDOTOOL_OPENSSL_BINARY ${TOOLS_INSTALL_DIR}/openssl)
    set(FDOTOOL_BIT4X_PKI_LIBRARY ${TOOLS_INSTALL_DIR}/libbit4xpki.so)
endif ()

set(FDOTOOL_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX})
