#set(CPACK_PACKAGE_NAME "Firma Digitale Odoo")
set(CPACK_PACKAGE_VENDOR "Seedoo")

set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "0")
set(CPACK_PACKAGE_VERSION_PATCH "0")

set(CPACK_PACKAGE_VERSION "${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}")
set(CPACK_PACKAGE_CONTACT "sadylan@gmail.com")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Tool per l'integrazione della Firma Digitale su Odoo")
set(CPACK_PACKAGE_FILE_NAME "fdotool-${CPACK_PACKAGE_VERSION}")
set(CPACK_PACKAGE_EXECUTABLES fdotool "FDO Tool")

#set(CPACK_RESOURCE_FILE_LICENSE "LICENSE.txt")
#set(CPACK_RESOURCE_FILE_README "README.txt")
#set(CPACK_RESOURCE_FILE_WELCOME "WELCOME.txt")

list(APPEND CPACK_COMPONENTS_ALL fdotool OpenSSLPatched)

set(CPACK_COMPONENT_FDOTOOL_DISPLAY_NAME "FDO Tool")
set(CPACK_COMPONENT_FDOTOOL_DESCRIPTION "Tool per la firma digitale Odoo")
set(CPACK_COMPONENT_FDOTOOL_REQUIRED TRUE)
set(CPACK_COMPONENT_FDOTOOL_DEPENDS OpenSSLPatched)

if (WIN32 OR APPLE)
    list(APPEND CPACK_COMPONENTS_ALL qtlibs)
    set(CPACK_COMPONENT_QTLIBS_DISPLAY_NAME "Qt libs")
    set(CPACK_COMPONENT_QTLIBS_DESCRIPTION "Needed Qt libraries")
    set(CPACK_COMPONENT_QTLIBS_REQUIRED TRUE)

    list(APPEND CPACK_COMPONENT_FDOTOOL_DEPENDS qtlibs)
endif ()

if (UNIX AND NOT APPLE)
    set(CPACK_GENERATOR "DEB")

    #    set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "i386")
    #    set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "amd64")

    set(CPACK_DEBIAN_PACKAGE_SECTION "misc")
    set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
    set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS TRUE)

    set(CPACK_DEBIAN_PACKAGE_DEPENDS "libengine-pkcs11-openssl, opensc-pkcs11")
elseif (WIN32)
    set(CPACK_GENERATOR "WIX")

    set(CPACK_WIX_PRODUCT_GUID "4B6A8129-DB7E-43BF-A00B-2760DF6D66ED")
    set(CPACK_WIX_UPGRADE_GUID "377580CA-C1E4-4B9A-94AF-C53DAF889A75")
    set(CPACK_WIX_PATCH_FILE "${CMAKE_CURRENT_SOURCE_DIR}/cmake/patch.xml")
    set(CPACK_WIX_EXTRA_SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/cmake/windows-registry-entries.wxs")
    set(CPACK_WIX_PROPERTY_ARPHELPLINK "http://www.seedoo.it")
    set(CPACK_WIX_PROPERTY_ARPSIZE "50000")

    set(CPACK_PACKAGE_INSTALL_DIRECTORY "FDO Tool ${CPACK_PACKAGE_VERSION}")
    set(CPACK_PACKAGE_ICON "icons/windows/icon-256.ico")
elseif (APPLE)
    #    set(CPACK_GENERATOR "OSXX11")
    set(CPACK_GENERATOR "Bundle")
endif ()

include(CPack)
